spring:
  application:
    name: buiness8001               #微服务调用时的名字
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/   #Eureka的地址
  instance:
    instance-id: business8001  #注册到eureka中的名字
    prefer-ip-address: true #表示微服务显示IP